[workspace]
members = [
    "cores/common",
    "cores/nintendo/*",
    "frontend/*",
    "frontend/desktop/frontend",
    "frontend/desktop/frontend/nintendo/*",
    "util",
    "logger",
]
# Required to determine version for wgpu
resolver = "2"
