[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Backends.
gbc = {path = "../../cores/nintendo/gbc"}

# Logger.
logger = {path = "../../logger"}

# Frontend utility crates.
imgui = {path = "imgui"}
file_dialogue = {path = "file_dialogue"}