[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Backends.
gbc = {path = "../../cores/nintendo/gbc"}

# Logger.
logger = {path = "../../logger"}

# Frontend utility crates.
imgui = {path = "imgui"}

# Generic frontend crate. 
frontend = {path = "frontend"}

# GBC frontend crate.
gbc_frontend = {path = "frontend/nintendo/gbc_frontend"}

# File dialogue crate.
rfd = "0.8.4"
