[package]
name = "file_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Logger crate.
logger = {path = "../../../logger"}

# File dialogue crate.
rfd = "0.8.4"