[package]
name = "common-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Priority queue, mainly for schedulers.
priority-queue = "1.2.2"

# Utility crate.
util = {path = "../../util"}